### ISSUE TITLE
Simple load .RAW from SDcard.

### ISSUE THREAD

**Issue by fredericplante** [ghlawrence2000/UTFT_SdRaw#1]
Hi!

All you work is great, I thank you for you passion. I was wondering if you could build a simple SD_RAW expample that would simply load a RAW file from sdcard. I I basically just want to use a 1,8 inch NON-Touch TFTscreen and I can't figure out what you are doing. 

By the way I try the SDraw seral exaple, and t return this:

C:\Documents and Settings\So sory\My Documents\Arduino\libraries\UTFT\UTFT.cpp:76:63: note: #pragma message: Compiling for Arduino Due (AT91SAM3X8E)...
   #pragma message("Compiling for Arduino Due (AT91SAM3X8E)...")
                                                               ^
UTFT_SdRaw\UTFT_SdRaw.cpp.o: In function `PrintFile::write(unsigned char const*, unsigned int)':
C:\Documents and Settings\So sory\My Documents\Arduino\libraries\SdFat/FatLib/ArduinoFiles.h:109: undefined reference to`FatFile::write(void const_, unsigned int)'
UTFT_SdRaw\UTFT_SdRaw.cpp.o: In function `FatFile::write(unsigned char)':
C:\Documents and Settings\So sory\My Documents\Arduino\libraries\SdFat/FatLib/FatFile.h:893: undefined reference to`FatFile::write(void const_, unsigned int)'
collect2.exe: error: ld returned 1 exit status
Error compiling.

Saw this before?

**Comment by ghlawrence2000** [comment]
Hello Frederic,

I am sorry you are having problems with UTFT_SdRaw. Could you tell me if you have SdFat installed from here :- [https://github.com/greiman/SdFat](url)? I have just noticed there is a new version, maybe there are changes which now don't work with UTFT_SdRaw, I will check and get back to you.

Regards,

Graham

**Comment by fredericplante** [comment]
https://github.com/greiman/SdFat

This page return a 404 error

**Comment by fredericplante** [comment]
Hemm possible.  the dates and the content of the zip file seem to match. I probably took it their, I think. Althout your link content does not seam to work.

**Comment by ghlawrence2000** [comment]
Hello Frederic,

Which version of the Arduino IDE are you using? I tested using IDE 1.6.5 and 1.6.8 without any problems.

G

**Comment by fredericplante** [comment]
I've just made a fresh copy of the Adruino folder and work space, following the instruction in the Programing port experience, work fine. And you are right, all is fine.

So thank you for your patience.
